FROM python:3.11.14-alpine
RUN adduser -D microblog

RUN apk update && apk upgrade --no-cache

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

ARG APP_VERSION="unknown"

ENV APP_VERSION=${APP_VERSION}

# RUN <<-EOF
#     python -m venv .venv
#     .venv/bin/pip3 install -r requirements.txt
# EOF

RUN <<-EOF
    python -m pip install --upgrade pip setuptools wheel 
    python -m venv .venv
    .venv/bin/pip install --upgrade pip setuptools wheel
    .venv/bin/pip install -r requirements.txt
EOF

ENV FLASK_APP microblog.py

RUN <<-EOF
    chmod +x boot.sh
    chown -R microblog:microblog ./
EOF

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]